eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka

server:
  port: 9100
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service-provider
          uri: lb://movie-service-provider
          predicates:
            - Path=/movie/**
